#!/usr/bin/env python

#### This is a scirpt that submits jobs for all GFF subfiles ####

# import packages 
import argparse, os 

# Set command line arguments 
parser = argparse.ArgumentParser(description = "submit jobs for all GFF subfiles")
parser.add_argument("GFF_list", type = str, help = "input a list fo GFF subfiles (.txt), which is generated by splitting the OGS 2.0 annotation file (.gff3)")
parser.add_argument("population", type = str, help = "assgin the population to use")
args = parser.parse_args()

# Read in a txt file with all GFF subfile names and submit jobs accordingly
with open(args.GFF_list, "r") as list: 
	for i in list:
		file = i.rstrip("\r\n")
		os.system("sbatch S4b_job_submission.sh " + file + " " + args.population + " 0f")   # run 0f 
		os.system("sbatch S4b_job_submission.sh " + file + " " + args.population + " 4f")   #run 4f 
